#: import BgBoxLayout Custom_Layouts
#: import BgStackLayout Custom_Layouts

Interface:

    orientation: 'vertical'
    padding: [dp(10), dp(10), dp(10), dp(10)]
    spacing: dp(5)

    Label:

        text: 'ChatGPT Clone'
        size_hint: 1, 0.05

    ScrollView:

        size_hint: 1, 0.8
        bar_margin: 20
        bar_width: 15

        BgBoxLayout:

            id: stackLayout
            size_hint_y: None
            height: self.minimum_height

    TextInput:

        id: textInput
        hint_text: 'Ide írhatod a kérésed/kérdésed'
        size_hint: 1, 0.1

    BgBoxLayout:

        size_hint: 1, 0.05

        Button:

            text: 'Küld'
            on_release: root.send()

        Button:

            text: 'Töröl'
            on_release: root.clear()

