#: import BgBoxLayout Custom_Layouts

Interface:

    orientation: 'vertical'
    padding: [dp(10), dp(10), dp(10), dp(10)]
    spacing: dp(5)
    hex_code: '#574bc9'
    alpha: 0.2


    BgBoxLayout:

        hex_code: '#574bc9'
        alpha: 0.2
        size_hint: 1, 0.05

        Label:

            text: 'ChatGPT Clone'

    ScrollView:

        size_hint: 1, 0.9
        bar_margin: 20
        bar_width: 15

        BgBoxLayout:

            id: conversation
            spacing: 3
            orientation: 'vertical'

    TextInput:

        id: textInput
        hint_text: 'Ide írhatod a kérésed/kérdésed'
        size_hint: 1, 0.1

    BoxLayout:

        size_hint: 1, 0.05

        Button:

            text: 'Küld'
            on_release: root.question()

        Button:

            text: 'Töröl'
            on_release: root.clear()

